### ISSUE TITLE
Access tokens have expiration date that is not handled in the app

### ISSUE THREAD

**Issue by MoridinBG** [GGLozanov/GitHubExplorer#6]
# **Bug Report**

Bug Name: Access tokens are not validated for expiration
Severity: **HIGH**
Priority: **HIGH**
Assigned to: @GGLozanov @alexvidenov
Reported By: @MoridinBG 
Reported On: 07.07.2020
Reason: Developer oversight
Environment: Any

# **Description**

Access tokens can expire and will eventually become invalid, but this is not handled in the app so authenticated requests will start to fail

# **Steps to Reproduce**

1. Login with an unauthorised GitHub account to the app.
2. Wait
3. Use authenticated functionality 

# **Potential Fix**
Verify token expiration and renew when needed

**Comment by GGLozanov** [comment]
I did some research and it turns out that [access token expiry](https://github.community/t/api-access-token-expiry/14522) is a feature that needs to be manually enabled in a given OAuth app and is still discouraged for mainstream use due to being in Beta. Normally, tokens can be revoked in several ways (none of which are of major concern to us; we only do it through the UI), and using [**refresh tokens** is part of the aforementioned expiry feature](https://developer.github.com/apps/building-github-apps/refreshing-user-to-server-access-tokens/).

I do not believe that we should be enforcing such a high barrier of security at this stage, but that's my view on the matter. The issue may persist if we wish.
